version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    command: sh -c "uvicorn api.main:app --port 8080 --host 0.0.0.0"
    env_file:
      - app/.env
    ports:
      - 8000:8080